[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
example = "BQJrDLm7z8NPnE45oNLfWXDzudhBHSDWTsKadxmU4FYE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
